-

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -86,9 +86,9 @@ jobs:
         with:
           sarif_file: snyk_code.sarif
 
-      - name: Fail job if scan failed
-        if: ${{ steps.code_scan.outcome == 'failure' }}
-        run: exit 1
+      # - name: Fail job if scan failed
+      #   if: ${{ steps.code_scan.outcome == 'failure' }}
+      #   run: exit 1
 
   docker_build_push:
     permissions:
@@ -148,9 +148,9 @@ jobs:
         with:
           sarif_file: snyk.sarif
 
-      - name: Fail job if scan failed
-        if: ${{ inputs.dockerScanDisabled == false && steps.docker_scan.outcome == 'failure' }}
-        run: exit 1
+      # - name: Fail job if scan failed
+      #   if: ${{ inputs.dockerScanDisabled == false && steps.docker_scan.outcome == 'failure' }}
+      #   run: exit 1
       
   helm_build_push:
     permissions:
@@ -218,9 +218,9 @@ jobs:
         with:
           sarif_file: snyk.sarif
 
-      - name: Fail job if scan failed
-        if: ${{ inputs.helmScanDisabled == false && steps.helm_scan.outcome == 'failure' }}
-        run: exit 1
+      # - name: Fail job if scan failed
+      #   if: ${{ inputs.helmScanDisabled == false && steps.helm_scan.outcome == 'failure' }}
+      #   run: exit 1
 
       - name: Package Chart
         run: helm package --version ${{ inputs.version }} --app-version v${{ inputs.version }} .
